name: intercom_test_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  flutter: ^3.5.0
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  intercom_flutter: ^9.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
